### ISSUE TITLE
No link to bitbucket?

### ISSUE THREAD

**Issue by mribau** [valenssoftware/bamboo-templatedplans-plugin#11]
The readme states "The code management is migrated to Bitbucket, I will leave this copy as reference only." but there is no link to the new repo.

**Comment by giulio1979** [comment]
Yes, but only selected organisations have access to latest code on https://bitbucket.org/iuliushutuleac/ 

Unfortunatelly the effort I put into this is big and I am trying to protect a bit the latest code since latest is licensed kinda (last free version has all features of paid version but if you want to support further development, buy a license)

**Comment by giulio1979** [comment]
Hi there,

I updated descriptions so I try to make it more clear. The move doesnt mean I stopped supporting this version, in case of issues I will continue to support you guys just future versions will have a bit more strict control over source code I think (at least for now)

J

**Comment by mribau** [comment]
Oh! Thank you for explaining. I did not realize there was a new paid version. Perhaps you should also link to the marketplace listing if possible?

**Comment by giulio1979** [comment]
Done
